import { createContext, useContext, useState } from 'react';
import { cn } from '../lib/utils';

export type Language = 'en' | 'fr';

export const translations = {
  en: {
    directory: 'Directory',
    comparison: 'Comparison Engine',
    analytics: 'Analytics',
    searchPlaceholder: 'Search cooperatives...',
    allRegions: 'All Regions',
    members: 'Members',
    score: 'Score',
    viewDetails: 'View Details',
    compare: 'Compare',
    backToDirectory: 'Back to Directory',
    interactiveComparison: 'Interactive Comparison',
    analyzingMetrics: 'Analyzing metrics across coffee cooperatives.',
    selectCooperatives: 'Select Cooperatives',
    selectTop4: 'Select Top 4',
    clearAll: 'Clear All',
    selectMetrics: 'Select Metrics to Compare',
    exportCSV: 'Export CSV',
    detailedMatrix: 'Detailed Comparison Matrix',
    downloadReport: 'Download Report',
    established: 'Established',
    production: 'Annual Production',
    metric: 'Metric',
    addToComparison: 'Add to Comparison',
    removeFromComparison: 'Remove from Comparison',
    searchMetrics: 'Search metrics...',
    cuppingScore: 'Cupping Score',
    womenMembers: 'Women Members',
    youthMembers: 'Youth Members',
    totalArea: 'Total Area',
    treeCount: 'Tree Count',
    households: 'Households',
    overview: 'Overview',
    productionStats: 'Production Stats',
    memberDemographics: 'Member Demographics',
    sensoryProfile: 'Sensory Profile',
    sensoryProfileNotEvaluated: 'No cupping panel recorded yet for this cooperative.',
    location: 'Location',
    description: 'Description',
    aroma: 'Aroma',
    acidity: 'Acidity',
    body: 'Body',
    sweetness: 'Sweetness',
    aftertaste: 'Aftertaste',
    genderDistribution: 'Gender Distribution',
    men: 'Men',
    women: 'Women',
    youthRepresentation: 'Youth Representation',
    socialImpact: 'Social Impact',
    beneficiaryHouseholds: 'Beneficiary Households',
    productionCapacity: 'Production Capacity',
    coffeeTrees: 'Coffee Trees',
    productionRevenueTrends: 'Production & Revenue Trends',
    varieties: 'Varieties',
    sustainabilityFocus: 'Sustainability Focus',
    selectACooperative: 'Select a Cooperative',
    selectACooperativeDesc: 'Choose a cooperative from the list to view its detailed profile, metrics, and sensory data.',
    platform: 'Platform',
    marketplace: 'Marketplace',
    impactReports: 'Impact Reports',
    contact: 'Contact',
    support: 'Support',
    partnerships: 'Partnerships',
    privacyPolicy: 'Privacy Policy',
    allRightsReserved: 'All rights reserved.',
    systemStatus: 'System Status',
    operational: 'Operational',
    coopsSelected: 'Coops Selected',
    compareNow: 'Compare Now',
    platformDesc: 'Empowering coffee cooperatives through data-driven insights and market connectivity. Bridging the gap between specialty producers and global roasters.',
    stagingArea: 'AI Staging Area',
    coopPortal: 'Coop Portal',
    cooperatives: 'Cooperatives',
    login: 'Login',
    logout: 'Logout',
    uploadPDF: 'Upload PDF/Image',
    parsingData: 'AI is parsing the document...',
    reviewData: 'Review Parsed Data',
    saveToDirectory: 'Save to Directory',
    coopManagerPortal: 'Cooperative Manager Portal',
    updateProfile: 'Update Profile',
    productionWizard: 'Production Update Wizard',
    step: 'Step',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit',
    success: 'Success',
    error: 'Error',
    loading: 'Loading...',
    admin: 'Admin',
    welcome: 'Welcome',
    manageCoop: 'Manage your cooperative profile and production data.',
    dropFiles: 'Drop files here or click to upload',
    supportedFormats: 'Supported formats: PDF, PNG, JPG',
    processing: 'Processing...',
    confirmAndSave: 'Confirm and Save',
    discard: 'Discard',
    noStagingData: 'No staging data available. Upload a document to get started.',
    unauthorized: 'You are not authorized to view this page.',
    pleaseLogin: 'Please login to access the portal.',
    managerEmail: 'Manager Email (Invitation)',
    inviteManager: 'Invite a manager to this cooperative',
    managerInvited: 'Manager successfully invited!',
    invalidManagerEmail: 'Invalid manager email address.',
    approveConfirmInvite: 'Publish "{name}" to the public directory?\n\n⚠️ {email} will become its MANAGER and can edit the public profile. Only approve if you trust this email.',
    approveConfirmNoInvite: 'Publish "{name}" to the public directory? No manager is invited.',
    userProfile: 'User Profile',
    phoneNumber: 'Phone Number',
    bio: 'Bio',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    displayName: 'Display Name',
    deleteCooperative: 'Delete Cooperative',
    confirmDelete: 'Are you sure you want to delete this cooperative? This action cannot be undone.',
    editCooperative: 'Edit Cooperative',
    addCooperative: 'Add Cooperative',
    newCooperative: 'New Cooperative',
    certifications: 'Certifications',
    about: 'About',
    // EUDR badge — legally scoped wording: geolocation readiness ONLY,
    // never a deforestation-free claim. Keep EN and FR strictly equivalent.
    eudrTitle: 'EUDR Geolocation Readiness',
    eudrReady: 'EUDR Geolocation-Ready',
    eudrIncomplete: 'EUDR — Data Incomplete',
    eudrScoreLabel: 'overall data readiness',
    eudrFarmsGps: 'farms geolocation-ready',
    eudrAsOf: 'Computed',
    eudrFromFile: 'from registry',
    eudrClaimScope: 'Attests plot geolocation readiness only (EUDR Art. 2(28) — point coordinates, ≥6 decimals). Not a deforestation-free assessment.',
    eudrAdminTitle: 'EUDR Compliance (admin)',
    eudrAdminHelp: 'Paste the eudrCompliance object from tools/eudr output (eudr_compliance.json). Validated before writing; rules reject non-admin writes.',
    eudrSelectCoop: 'Select cooperative',
    eudrPaste: 'Paste eudrCompliance JSON here',
    eudrSave: 'Publish badge data',
    eudrSaved: 'EUDR data published.',
    eudrInvalid: 'Invalid JSON or wrong shape:',
    eudrCoopMismatch: 'The pasted file was computed for a different cooperative:',
    howItWorksTitle: 'How CongoFarmers Works',
    howItWorksSubtitle: 'From farm to buyer — a transparent, data-driven pipeline for specialty coffee discovery.',
    step1Title: 'Cooperatives submit data',
    step1Desc: 'Cooperative managers upload a PDF profile or fill in the portal form. AI extracts structured data instantly.',
    step2Title: 'AI parses & structures',
    step2Desc: 'Gemini AI reads the document and maps it to a standard schema — members, altitude, certifications, cupping scores.',
    step3Title: 'Admin reviews & approves',
    step3Desc: 'Our team verifies the parsed data in the staging area before it goes live. No unverified data reaches buyers.',
    step4Title: 'Published to the directory',
    step4Desc: 'Approved cooperatives appear in the searchable directory, Best of Congo leaderboard, and comparison engine.',
    close: 'Close',
  },
  fr: {
    directory: 'Répertoire',
    comparison: 'Moteur de Comparaison',
    analytics: 'Analyses',
    searchPlaceholder: 'Rechercher des coopératives...',
    allRegions: 'Toutes les Régions',
    members: 'Membres',
    score: 'Score',
    viewDetails: 'Voir Détails',
    compare: 'Comparer',
    backToDirectory: 'Retour au Répertoire',
    interactiveComparison: 'Comparaison Interactive',
    analyzingMetrics: 'Analyse des indicateurs des coopératives de café.',
    selectCooperatives: 'Sélectionner des Coopératives',
    selectTop4: 'Top 4',
    clearAll: 'Tout Effacer',
    selectMetrics: 'Indicateurs à Comparer',
    exportCSV: 'Exporter CSV',
    detailedMatrix: 'Matrice de Comparaison Détaillée',
    downloadReport: 'Télécharger le Rapport',
    established: 'Établi en',
    production: 'Production Annuelle',
    metric: 'Indicateur',
    addToComparison: 'Ajouter à la Comparaison',
    removeFromComparison: 'Retirer de la Comparaison',
    searchMetrics: 'Rechercher des indicateurs...',
    cuppingScore: 'Score de Dégustation',
    womenMembers: 'Femmes Membres',
    youthMembers: 'Jeunes Membres',
    totalArea: 'Superficie Totale',
    treeCount: 'Nombre d\'Arbres',
    households: 'Ménages',
    overview: 'Aperçu',
    productionStats: 'Stats de Production',
    memberDemographics: 'Démographie des Membres',
    sensoryProfile: 'Profil Sensoriel',
    sensoryProfileNotEvaluated: 'Aucune dégustation enregistrée pour cette coopérative.',
    location: 'Emplacement',
    description: 'Description',
    aroma: 'Arôme',
    acidity: 'Acidité',
    body: 'Corps',
    sweetness: 'Douceur',
    aftertaste: 'Arrière-goût',
    genderDistribution: 'Répartition par Sexe',
    men: 'Hommes',
    women: 'Femmes',
    youthRepresentation: 'Représentation des Jeunes',
    socialImpact: 'Impact Social',
    beneficiaryHouseholds: 'Ménages Bénéficiaires',
    productionCapacity: 'Capacité de Production',
    coffeeTrees: 'Caféiers',
    productionRevenueTrends: 'Tendances de Production et Revenus',
    varieties: 'Variétés',
    sustainabilityFocus: 'Focus Durabilité',
    selectACooperative: 'Sélectionnez une Coopérative',
    selectACooperativeDesc: 'Choisissez une coopérative dans la liste pour voir son profil détaillé, ses indicateurs et ses données sensorielles.',
    platform: 'Plateforme',
    marketplace: 'Marché',
    impactReports: 'Rapports d\'Impact',
    contact: 'Contact',
    support: 'Support',
    partnerships: 'Partenariats',
    privacyPolicy: 'Politique de Confidentialité',
    allRightsReserved: 'Tous droits réservés.',
    systemStatus: 'Statut du Système',
    operational: 'Opérationnel',
    coopsSelected: 'Coops Sélectionnées',
    compareNow: 'Comparer Maintenant',
    platformDesc: 'Autonomiser les coopératives de café grâce à des données et à la connectivité du marché. Combler le fossé entre les producteurs de spécialité et les torréfacteurs mondiaux.',
    stagingArea: 'Zone de Transit IA',
    coopPortal: 'Portail Coop',
    cooperatives: 'Coopératives',
    login: 'Connexion',
    logout: 'Déconnexion',
    uploadPDF: 'Télécharger PDF/Image',
    parsingData: 'L\'IA analyse le document...',
    reviewData: 'Réviser les Données Analysées',
    saveToDirectory: 'Enregistrer dans le Répertoire',
    coopManagerPortal: 'Portail Gestionnaire de Coopérative',
    updateProfile: 'Mettre à Jour le Profil',
    productionWizard: 'Assistant de Mise à Jour de Production',
    step: 'Étape',
    next: 'Suivant',
    previous: 'Précédent',
    submit: 'Soumettre',
    success: 'Succès',
    error: 'Erreur',
    loading: 'Chargement...',
    admin: 'Admin',
    welcome: 'Bienvenue',
    manageCoop: 'Gérez votre profil de coopérative et vos données de production.',
    dropFiles: 'Déposez les fichiers ici ou cliquez pour télécharger',
    supportedFormats: 'Formats supportés : PDF, PNG, JPG',
    processing: 'Traitement...',
    confirmAndSave: 'Confirmer et Enregistrer',
    discard: 'Abandonner',
    noStagingData: 'Aucune donnée en transit. Téléchargez un document pour commencer.',
    unauthorized: 'Vous n\'êtes pas autorisé à consulter cette page.',
    pleaseLogin: 'Veuillez vous connecter pour accéder au portail.',
    managerEmail: 'Email du Gestionnaire (Invitation)',
    inviteManager: 'Inviter un gestionnaire pour cette coopérative',
    managerInvited: 'Gestionnaire invité avec succès !',
    invalidManagerEmail: 'Adresse email du gestionnaire invalide.',
    approveConfirmInvite: 'Publier « {name} » dans l\'annuaire public ?\n\n⚠️ {email} en deviendra le GESTIONNAIRE et pourra modifier le profil public. N\'approuvez que si vous faites confiance à cet email.',
    approveConfirmNoInvite: 'Publier « {name} » dans l\'annuaire public ? Aucun gestionnaire invité.',
    userProfile: 'Profil Utilisateur',
    phoneNumber: 'Numéro de Téléphone',
    bio: 'Bio',
    saveChanges: 'Enregistrer les Modifications',
    cancel: 'Annuler',
    displayName: 'Nom d\'affichage',
    deleteCooperative: 'Supprimer la Coopérative',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer cette coopérative ? Cette action est irréversible.',
    editCooperative: 'Modifier la Coopérative',
    addCooperative: 'Ajouter une Coopérative',
    newCooperative: 'Nouvelle Coopérative',
    certifications: 'Certifications',
    about: 'À propos',
    // Badge EUDR — formulation juridiquement cadrée : préparation à la
    // géolocalisation UNIQUEMENT, jamais une déclaration « zéro déforestation ».
    eudrTitle: 'Préparation Géolocalisation EUDR',
    eudrReady: 'Géolocalisation EUDR Prête',
    eudrIncomplete: 'EUDR — Données Incomplètes',
    eudrScoreLabel: 'de préparation globale des données',
    eudrFarmsGps: 'fermes prêtes en géolocalisation',
    eudrAsOf: 'Calculé le',
    eudrFromFile: 'à partir du registre',
    eudrClaimScope: 'Atteste uniquement la préparation à la géolocalisation des parcelles (EUDR Art. 2(28) — coordonnées ponctuelles, ≥6 décimales). Ce n\'est pas une évaluation « zéro déforestation ».',
    eudrAdminTitle: 'Conformité EUDR (admin)',
    eudrAdminHelp: 'Collez l\'objet eudrCompliance produit par tools/eudr (eudr_compliance.json). Validé avant écriture ; les règles rejettent toute écriture non-admin.',
    eudrSelectCoop: 'Sélectionner la coopérative',
    eudrPaste: 'Collez le JSON eudrCompliance ici',
    eudrSave: 'Publier les données du badge',
    eudrSaved: 'Données EUDR publiées.',
    eudrInvalid: 'JSON invalide ou structure incorrecte :',
    eudrCoopMismatch: 'Le fichier collé a été calculé pour une autre coopérative :',
    howItWorksTitle: 'Comment fonctionne CongoFarmers',
    howItWorksSubtitle: 'De la ferme à l\'acheteur — un pipeline transparent et basé sur les données pour la découverte du café de spécialité.',
    step1Title: 'Les coopératives soumettent des données',
    step1Desc: 'Les gestionnaires téléchargent un profil PDF ou remplissent le formulaire du portail. L\'IA extrait les données instantanément.',
    step2Title: 'L\'IA analyse et structure',
    step2Desc: 'Gemini AI lit le document et le mappe vers un schéma standard — membres, altitude, certifications, scores de dégustation.',
    step3Title: 'L\'admin révise et approuve',
    step3Desc: 'Notre équipe vérifie les données analysées dans la zone de transit avant leur mise en ligne. Aucune donnée non vérifiée n\'atteint les acheteurs.',
    step4Title: 'Publié dans le répertoire',
    step4Desc: 'Les coopératives approuvées apparaissent dans le répertoire consultable, le classement Best of Congo et le moteur de comparaison.',
    close: 'Fermer',
  }
};

export const LanguageContext = createContext<{
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}>({
  lang: 'en',
  setLang: () => {},
  t: (key) => translations.en[key]
});

export const useTranslation = () => useContext(LanguageContext);

export const LanguageSwitcher = () => {
  const { lang, setLang } = useTranslation();
  return (
    <div className="flex items-center gap-2 bg-stone-100 p-1 rounded-lg border border-stone-200">
      <button
        onClick={() => setLang('en')}
        className={cn(
          "px-3 py-2 min-h-[44px] text-[10px] font-black uppercase tracking-widest rounded-md transition-all flex items-center",
          lang === 'en' ? "bg-white text-amber-900 shadow-sm" : "text-stone-400 hover:text-stone-600"
        )}
      >
        EN
      </button>
      <button
        onClick={() => setLang('fr')}
        className={cn(
          "px-3 py-2 min-h-[44px] text-[10px] font-black uppercase tracking-widest rounded-md transition-all flex items-center",
          lang === 'fr' ? "bg-white text-amber-900 shadow-sm" : "text-stone-400 hover:text-stone-600"
        )}
      >
        FR
      </button>
    </div>
  );
};

export function useLanguageProvider() {
  const [lang, setLang] = useState<Language>('en');
  const t = (key: keyof typeof translations.en): string => {
    return translations[lang][key] || translations.en[key];
  };
  return { lang, setLang, t };
}
