import { createContext, useContext, useState } from 'react';
import { cn } from '../lib/utils';

export type Language = 'en' | 'fr';

export const translations = {
  en: {
    directory: 'Directory',
    comparison: 'Comparison Engine',
    analytics: 'Analytics',
    searchPlaceholder: 'Search cooperatives...',
    allRegions: 'All Regions',
    members: 'Members',
    score: 'Score',
    viewDetails: 'View Details',
    compare: 'Compare',
    backToDirectory: 'Back to Directory',
    interactiveComparison: 'Interactive Comparison',
    analyzingMetrics: 'Analyzing metrics across coffee cooperatives.',
    selectCooperatives: 'Select Cooperatives',
    selectTop4: 'Select Top 4',
    clearAll: 'Clear All',
    selectMetrics: 'Select Metrics to Compare',
    exportCSV: 'Export CSV',
    detailedMatrix: 'Detailed Comparison Matrix',
    downloadReport: 'Download Report',
    established: 'Established',
    production: 'Annual Production',
    metric: 'Metric',
    addToComparison: 'Add to Comparison',
    removeFromComparison: 'Remove from Comparison',
    searchMetrics: 'Search metrics...',
    cuppingScore: 'Cupping Score',
    womenMembers: 'Women Members',
    youthMembers: 'Youth Members',
    totalArea: 'Total Area',
    treeCount: 'Tree Count',
    households: 'Households',
    overview: 'Overview',
    productionStats: 'Production Stats',
    memberDemographics: 'Member Demographics',
    sensoryProfile: 'Sensory Profile',
    location: 'Location',
    description: 'Description',
    aroma: 'Aroma',
    acidity: 'Acidity',
    body: 'Body',
    sweetness: 'Sweetness',
    aftertaste: 'Aftertaste',
    genderDistribution: 'Gender Distribution',
    men: 'Men',
    women: 'Women',
    youthRepresentation: 'Youth Representation',
    socialImpact: 'Social Impact',
    beneficiaryHouseholds: 'Beneficiary Households',
    productionCapacity: 'Production Capacity',
    coffeeTrees: 'Coffee Trees',
    productionRevenueTrends: 'Production & Revenue Trends',
    varieties: 'Varieties',
    sustainabilityFocus: 'Sustainability Focus',
    selectACooperative: 'Select a Cooperative',
    selectACooperativeDesc: 'Choose a cooperative from the list to view its detailed profile, metrics, and sensory data.',
    platform: 'Platform',
    marketplace: 'Marketplace',
    impactReports: 'Impact Reports',
    contact: 'Contact',
    support: 'Support',
    partnerships: 'Partnerships',
    privacyPolicy: 'Privacy Policy',
    allRightsReserved: 'All rights reserved.',
    systemStatus: 'System Status',
    operational: 'Operational',
    coopsSelected: 'Coops Selected',
    compareNow: 'Compare Now',
    platformDesc: 'Empowering coffee cooperatives through data-driven insights and market connectivity. Bridging the gap between specialty producers and global roasters.',
    stagingArea: 'AI Staging Area',
    coopPortal: 'Coop Portal',
    cooperatives: 'Cooperatives',
    login: 'Login',
    logout: 'Logout',
    uploadPDF: 'Upload PDF/Image',
    parsingData: 'AI is parsing the document...',
    reviewData: 'Review Parsed Data',
    saveToDirectory: 'Save to Directory',
    coopManagerPortal: 'Cooperative Manager Portal',
    updateProfile: 'Update Profile',
    productionWizard: 'Production Update Wizard',
    step: 'Step',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit',
    success: 'Success',
    error: 'Error',
    loading: 'Loading...',
    admin: 'Admin',
    welcome: 'Welcome',
    manageCoop: 'Manage your cooperative profile and production data.',
    dropFiles: 'Drop files here or click to upload',
    supportedFormats: 'Supported formats: PDF, PNG, JPG',
    processing: 'Processing...',
    confirmAndSave: 'Confirm and Save',
    discard: 'Discard',
    noStagingData: 'No staging data available. Upload a document to get started.',
    unauthorized: 'You are not authorized to view this page.',
    pleaseLogin: 'Please login to access the portal.',
    managerEmail: 'Manager Email (Invitation)',
    inviteManager: 'Invite a manager to this cooperative',
    managerInvited: 'Manager successfully invited!',
    userProfile: 'User Profile',
    phoneNumber: 'Phone Number',
    bio: 'Bio',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    displayName: 'Display Name',
    deleteCooperative: 'Delete Cooperative',
    confirmDelete: 'Are you sure you want to delete this cooperative? This action cannot be undone.',
    editCooperative: 'Edit Cooperative',
    addCooperative: 'Add Cooperative',
    newCooperative: 'New Cooperative',
    certifications: 'Certifications',
  },
  fr: {
    directory: 'Répertoire',
    comparison: 'Moteur de Comparaison',
    analytics: 'Analyses',
    searchPlaceholder: 'Rechercher des coopératives...',
    allRegions: 'Toutes les Régions',
    members: 'Membres',
    score: 'Score',
    viewDetails: 'Voir Détails',
    compare: 'Comparer',
    backToDirectory: 'Retour au Répertoire',
    interactiveComparison: 'Comparaison Interactive',
    analyzingMetrics: 'Analyse des indicateurs des coopératives de café.',
    selectCooperatives: 'Sélectionner des Coopératives',
    selectTop4: 'Top 4',
    clearAll: 'Tout Effacer',
    selectMetrics: 'Indicateurs à Comparer',
    exportCSV: 'Exporter CSV',
    detailedMatrix: 'Matrice de Comparaison Détaillée',
    downloadReport: 'Télécharger le Rapport',
    established: 'Établi en',
    production: 'Production Annuelle',
    metric: 'Indicateur',
    addToComparison: 'Ajouter à la Comparaison',
    removeFromComparison: 'Retirer de la Comparaison',
    searchMetrics: 'Rechercher des indicateurs...',
    cuppingScore: 'Score de Dégustation',
    womenMembers: 'Femmes Membres',
    youthMembers: 'Jeunes Membres',
    totalArea: 'Superficie Totale',
    treeCount: 'Nombre d\'Arbres',
    households: 'Ménages',
    overview: 'Aperçu',
    productionStats: 'Stats de Production',
    memberDemographics: 'Démographie des Membres',
    sensoryProfile: 'Profil Sensoriel',
    location: 'Emplacement',
    description: 'Description',
    aroma: 'Arôme',
    acidity: 'Acidité',
    body: 'Corps',
    sweetness: 'Douceur',
    aftertaste: 'Arrière-goût',
    genderDistribution: 'Répartition par Sexe',
    men: 'Hommes',
    women: 'Femmes',
    youthRepresentation: 'Représentation des Jeunes',
    socialImpact: 'Impact Social',
    beneficiaryHouseholds: 'Ménages Bénéficiaires',
    productionCapacity: 'Capacité de Production',
    coffeeTrees: 'Caféiers',
    productionRevenueTrends: 'Tendances de Production et Revenus',
    varieties: 'Variétés',
    sustainabilityFocus: 'Focus Durabilité',
    selectACooperative: 'Sélectionnez une Coopérative',
    selectACooperativeDesc: 'Choisissez une coopérative dans la liste pour voir son profil détaillé, ses indicateurs et ses données sensorielles.',
    platform: 'Plateforme',
    marketplace: 'Marché',
    impactReports: 'Rapports d\'Impact',
    contact: 'Contact',
    support: 'Support',
    partnerships: 'Partenariats',
    privacyPolicy: 'Politique de Confidentialité',
    allRightsReserved: 'Tous droits réservés.',
    systemStatus: 'Statut du Système',
    operational: 'Opérationnel',
    coopsSelected: 'Coops Sélectionnées',
    compareNow: 'Comparer Maintenant',
    platformDesc: 'Autonomiser les coopératives de café grâce à des données et à la connectivité du marché. Combler le fossé entre les producteurs de spécialité et les torréfacteurs mondiaux.',
    stagingArea: 'Zone de Transit IA',
    coopPortal: 'Portail Coop',
    cooperatives: 'Coopératives',
    login: 'Connexion',
    logout: 'Déconnexion',
    uploadPDF: 'Télécharger PDF/Image',
    parsingData: 'L\'IA analyse le document...',
    reviewData: 'Réviser les Données Analysées',
    saveToDirectory: 'Enregistrer dans le Répertoire',
    coopManagerPortal: 'Portail Gestionnaire de Coopérative',
    updateProfile: 'Mettre à Jour le Profil',
    productionWizard: 'Assistant de Mise à Jour de Production',
    step: 'Étape',
    next: 'Suivant',
    previous: 'Précédent',
    submit: 'Soumettre',
    success: 'Succès',
    error: 'Erreur',
    loading: 'Chargement...',
    admin: 'Admin',
    welcome: 'Bienvenue',
    manageCoop: 'Gérez votre profil de coopérative et vos données de production.',
    dropFiles: 'Déposez les fichiers ici ou cliquez pour télécharger',
    supportedFormats: 'Formats supportés : PDF, PNG, JPG',
    processing: 'Traitement...',
    confirmAndSave: 'Confirmer et Enregistrer',
    discard: 'Abandonner',
    noStagingData: 'Aucune donnée en transit. Téléchargez un document pour commencer.',
    unauthorized: 'Vous n\'êtes pas autorisé à consulter cette page.',
    pleaseLogin: 'Veuillez vous connecter pour accéder au portail.',
    managerEmail: 'Email du Gestionnaire (Invitation)',
    inviteManager: 'Inviter un gestionnaire pour cette coopérative',
    managerInvited: 'Gestionnaire invité avec succès !',
    userProfile: 'Profil Utilisateur',
    phoneNumber: 'Numéro de Téléphone',
    bio: 'Bio',
    saveChanges: 'Enregistrer les Modifications',
    cancel: 'Annuler',
    displayName: 'Nom d\'affichage',
    deleteCooperative: 'Supprimer la Coopérative',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer cette coopérative ? Cette action est irréversible.',
    editCooperative: 'Modifier la Coopérative',
    addCooperative: 'Ajouter une Coopérative',
    newCooperative: 'Nouvelle Coopérative',
    certifications: 'Certifications',
  }
};

export const LanguageContext = createContext<{
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}>({
  lang: 'en',
  setLang: () => {},
  t: (key) => translations.en[key]
});

export const useTranslation = () => useContext(LanguageContext);

export const LanguageSwitcher = () => {
  const { lang, setLang } = useTranslation();
  return (
    <div className="flex items-center gap-2 bg-stone-100 p-1 rounded-lg border border-stone-200">
      <button
        onClick={() => setLang('en')}
        className={cn(
          "px-3 py-2 min-h-[44px] text-[10px] font-black uppercase tracking-widest rounded-md transition-all flex items-center",
          lang === 'en' ? "bg-white text-amber-900 shadow-sm" : "text-stone-400 hover:text-stone-600"
        )}
      >
        EN
      </button>
      <button
        onClick={() => setLang('fr')}
        className={cn(
          "px-3 py-2 min-h-[44px] text-[10px] font-black uppercase tracking-widest rounded-md transition-all flex items-center",
          lang === 'fr' ? "bg-white text-amber-900 shadow-sm" : "text-stone-400 hover:text-stone-600"
        )}
      >
        FR
      </button>
    </div>
  );
};

export function useLanguageProvider() {
  const [lang, setLang] = useState<Language>('en');
  const t = (key: keyof typeof translations.en): string => {
    return translations[lang][key] || translations.en[key];
  };
  return { lang, setLang, t };
}
